
    -- cooking
    campfire    = { name = 'campfire',     label = 'Campfire Kit',     weight = 500,  type = 'item',  image = 'campfire.png',     unique = false,  useable = true,   shouldClose = true,  description = 'Used to set up a campfire', category = 'tools' },
    bread_sour  = { name = 'bread_sour',   label = 'Sourdough Bread',  weight = 100,  type = 'item',  image = 'bread_sour.png',   unique = false,  useable = true,   shouldClose = true,  description = 'Oven Fresh',          category = 'cooking' },
    cooked_fish = { name = 'cooked_fish',  label = 'Cooked Fish',      weight = 50,   type = 'item',  image = 'cooked_fish.png',  unique = false,  useable = true,   shouldClose = true,  description = 'ready for eating',    category = 'cooking' },
    cooked_meat = { name = 'cooked_meat',  label = 'Cooked Meat',      weight = 50,   type = 'item',  image = 'cooked_meat.png',  unique = false,  useable = true,   shouldClose = true,  description = 'ready for eating',    category = 'cooking' },
    egg         = { name = 'egg',          label = 'Egg',              weight = 100,  type = 'item',  image = 'egg.png',          unique = false,  useable = false,  shouldClose = true,  description = 'Cooking Ingredient',  category = 'cooking' },
    flour_wheat = { name = 'flour_wheat',  label = 'Wheat Flour',      weight = 100,  type = 'item',  image = 'flour_wheat.png',  unique = false,  useable = false,  shouldClose = true,  description = 'Cooking ingredient',  category = 'cooking' },
    milk        = { name = 'milk',         label = 'Milk',             weight = 100,  type = 'item',  image = 'milk.png',         unique = false,  useable = true,   shouldClose = true,  description = 'Dairy product',       category = 'cooking' },
    raw_fish    = { name = 'raw_fish',     label = 'Fish Meat',        weight = 50,   type = 'item',  image = 'raw_fish.png',     unique = false,  useable = true,   shouldClose = true,  description = 'ready for cooking',   category = 'general' },
    raw_meat    = { name = 'raw_meat',     label = 'Raw Meat',         weight = 50,   type = 'item',  image = 'raw_meat.png',     unique = false,  useable = true,   shouldClose = true,  description = 'ready for cooking',   category = 'general' },
